"""
06_train.py — Finnish BERT MLM pre-training loop.

Trains BertForMLM (05_model.py) on the pre-tokenised dataset (dataset.pt)
generated by 04_dataset.py.  No third-party libraries beyond PyTorch and
tqdm are used.

Academic references
-------------------
Devlin et al. 2019       — BERT: Pre-training of Deep Bidirectional Transformers
                           (arXiv:1810.04805)
Liu et al. 2019          — RoBERTa: A Robustly Optimized BERT Pretraining Approach
                           (arXiv:1907.11692)
Loshchilov & Hutter 2019 — Decoupled Weight Decay Regularization / AdamW
                           (arXiv:1711.05101)
Micikevicius et al. 2018 — Mixed Precision Training
                           (arXiv:1710.03740)
Xiong et al. 2020        — On Layer Normalization in the Transformer Architecture
                           (arXiv:2002.04745)
"""

import importlib.util
import math
import os
import random
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from tqdm.auto import tqdm  # auto → notebook widget in Colab, plain bar locally


# ── Load sibling modules via importlib ────────────────────────────────────────
# 04_dataset.py and 05_model.py begin with a digit, making them invalid Python
# identifiers.  importlib.util lets us load them by file path.

_SRC_DIR = Path(__file__).resolve().parent


def _load_src_module(module_name: str, filename: str):
    spec   = importlib.util.spec_from_file_location(module_name, _SRC_DIR / filename)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_dataset_mod = _load_src_module("dataset_04", "04_dataset.py")
_model_mod   = _load_src_module("model_05",   "05_model.py")

apply_masking  = _dataset_mod.apply_masking   # dynamic WWM masking function
load_tokenizer = _dataset_mod.load_tokenizer  # (vocab, merges) loader
BertForMLM     = _model_mod.BertForMLM        # pre-training model
BertConfig     = _model_mod.BertConfig        # model hyperparameters


# ── SECTION 1: CONFIG ─────────────────────────────────────────────────────────

@dataclass
class TrainingConfig:
    """
    All hyperparameters for Finnish BERT pre-training.

    Centralising configuration in a dataclass lets us serialise the full
    training setup into every checkpoint via config.__dict__, so every saved
    checkpoint is self-documenting and can be reproduced exactly.

    Sources: Devlin et al. 2019 (BERT), Liu et al. 2019 (RoBERTa),
             Loshchilov & Hutter 2019 (AdamW), Micikevicius et al. 2018 (fp16).
    """

    # ── Paths ──────────────────────────────────────────────────────────────────
    dataset_path: str = "data/processed/dataset.pt"
    # Pre-tokenised LongTensor file produced by 04_dataset.preprocess_and_save.

    tokenizer_dir: str = "data/tokenizer"
    # Directory with vocab.json + merges.txt from 03_tokenizer.py.

    checkpoint_dir: str = "checkpoints"
    # Local directory for checkpoint files.  Created automatically if absent.

    drive_checkpoint_dir: str = "/content/drive/MyDrive/Finnish-Embedding/checkpoints"
    # Google Drive mirror path.  Drive survives Colab VM resets (runtimes are
    # recycled every 8–12 h of inactivity); /content/ is ephemeral.

    # ── Training ───────────────────────────────────────────────────────────────
    batch_size: int = 128
    # Per-GPU micro-batch size.  128 fits an A100 40 GB at seq_len=128.  The
    # effective batch (batch_size × grad_accum_steps = 512) improves gradient
    # estimates — critical for MLM where only ~15% of tokens give signal per seq.

    grad_accum_steps: int = 4
    # Gradient accumulation steps.  effective_batch = 128 × 4 = 512.  Simulates
    # a 512-sample batch across four 128-sample forward passes, avoiding the
    # memory cost of a single 512-sample batch.

    max_steps: int = 45_000
    # Total optimizer update steps.  With 2 M samples, batch_size=128, drop_last:
    #   batches/epoch ≈ 2 000 000 / 128 = 15 625
    #   opt steps/epoch ≈ 15 625 / 4 = 3 906
    #   45 000 steps ≈ 11.5 epochs — ~30 min on A100.

    warmup_ratio: float = 0.10
    # Fraction of max_steps used for linear LR warmup → 4 500 warmup steps.
    # Required for Post-LN Transformers (Xiong et al. 2020): early-training
    # gradients through post-norm LayerNorm are large; a zero-start ramp lets
    # Adam's moment estimates stabilise before large parameter updates occur.

    # ── Optimizer ──────────────────────────────────────────────────────────────
    lr: float = 1e-4
    # Peak learning rate.  BERT paper: lr = 1e-4 for pre-training.

    weight_decay: float = 0.01
    # L2 regularisation applied only to weight matrices (not bias/LayerNorm).
    # BERT uses 0.01.  Loshchilov & Hutter 2019 show that penalising bias and
    # norm parameters reduces representational capacity without regularising
    # weight matrices — the intended target of weight decay.

    beta1: float = 0.9
    beta2: float = 0.999
    # Adam moment decay rates.  BERT: (0.9, 0.999).
    # RoBERTa uses beta2=0.98 to handle very large effective batches (8 K).
    # We keep 0.999 since our effective batch (512) is well below that regime.

    eps: float = 1e-8
    # Numerical stability term in AdamW denominator.

    max_grad_norm: float = 1.0
    # Gradient norm clipping.  RoBERTa (Liu et al. 2019) clips to 1.0 to
    # prevent rare gradient spikes from corrupting a model after many stable
    # training steps.

    # ── Checkpointing & Logging ────────────────────────────────────────────────
    checkpoint_every: int = 2_000
    # Save every 2 000 optimizer steps (~15 min on A100).  With a typical
    # 8–12 h Colab session, this yields at most 6 checkpoints before restart —
    # acceptable overhead at ~5 s per Drive write.

    log_every: int = 100
    # Print training metrics every 100 optimizer steps.

    # ── Colab ──────────────────────────────────────────────────────────────────
    use_drive: bool = True
    # Mirror each checkpoint to Google Drive for cross-session persistence.

    use_fp16: bool = True
    # fp16 automatic mixed precision (Micikevicius et al. 2018).  A100 Tensor
    # Cores run fp16 matrix multiplications at ~2× fp32 throughput.  GradScaler
    # prevents fp16 gradient underflow via dynamic loss scaling.

    seed: int = 42
    # Master random seed for torch and random.  Ensures reproducibility for
    # fresh training runs (but not for checkpoint resumes — DataLoader shuffle
    # state is not saved; see train() docstring for rationale).


# ── SECTION 2: LR SCHEDULER ───────────────────────────────────────────────────

def get_lr_scheduler(
    optimizer: torch.optim.Optimizer,
    warmup_steps: int,
    max_steps: int,
) -> torch.optim.lr_scheduler.LambdaLR:
    """
    Builds a learning rate schedule: linear warmup then cosine decay.

    Why linear warmup (Xiong et al. 2020, arXiv:2002.04745):
        BERT uses Post-LN — LayerNorm applied after the residual connection.
        In Post-LN networks, the gradient magnitude at early layers is
        sensitive to randomly initialised LayerNorm parameters; large learning
        rates in the first few steps can push these parameters into a bad
        basin from which recovery is slow.  Xiong et al. 2020 proved formally
        that Post-LN requires warmup while Pre-LN does not.  Starting lr at
        zero and ramping linearly over warmup_steps allows Adam's first- and
        second-moment estimates to stabilise before large parameter updates.

    Why cosine decay (Loshchilov & Hutter 2016, arXiv:1608.03983):
        After warmup, the multiplier follows a half-cosine curve from 1.0
        to 0.0.  Compared with the linear decay used in the original BERT:
          (a) Cosine spends more time near peak lr, where the gradient signal
              is richest and the model is still learning rapidly.
          (b) The smooth approach to zero avoids the abrupt drop of linear
              decay, which can destabilise the last training steps.
        RoBERTa (Liu et al. 2019) adopts cosine decay and reports a slight
        perplexity improvement over linear decay.

    Implementation via LambdaLR:
        LambdaLR multiplies the base lr by the scalar returned by lr_lambda.
        This avoids writing a custom scheduler class while supporting
        checkpoint/resume via scheduler.state_dict() / load_state_dict().

    Parameters
    ----------
    optimizer    : AdamW optimizer instance
    warmup_steps : length of linear warmup in optimizer steps
    max_steps    : total optimizer steps (cosine decay ends here)

    Returns
    -------
    LambdaLR scheduler (multiplier only; base lr is set on the optimizer).
    """
    def lr_lambda(current_step: int) -> float:
        if current_step < warmup_steps:
            # Linear ramp: 0 → 1 over warmup_steps steps
            return float(current_step) / float(max(1, warmup_steps))
        # Cosine decay: 1 → 0 over (max_steps − warmup_steps) remaining steps.
        # Clamp progress to [0, 1]: past max_steps the cosine would oscillate
        # back upward (cos(π × progress) for progress > 1 is no longer −1),
        # so without the clamp the LR could rise again after max_steps.
        progress = min(
            1.0,
            float(current_step - warmup_steps) / float(max(1, max_steps - warmup_steps)),
        )
        return max(0.0, 0.5 * (1.0 + math.cos(math.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


# ── SECTION 3: CHECKPOINTING ──────────────────────────────────────────────────

def save_checkpoint(
    checkpoint_dir: Path,
    global_step: int,
    epoch: int,
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    scheduler: torch.optim.lr_scheduler.LambdaLR,
    scaler: torch.cuda.amp.GradScaler,
    loss_history: List[float],
    config: TrainingConfig,
) -> Path:
    """
    Atomically writes a training checkpoint and optionally mirrors to Drive.

    Atomic write via os.replace:
        torch.save() writes the checkpoint file incrementally.  If the Colab
        VM is recycled mid-write (which happens silently during long runs), the
        partially written file is silently corrupt and unusable.
        Strategy: write to <name>.tmp first, then call os.replace() to rename
        it to the final path.  On POSIX (Linux, macOS — including Colab Ubuntu
        VMs), rename is guaranteed atomic when source and destination reside on
        the same filesystem: the OS either completes the rename or does not;
        there is no observable intermediate state.  The previous checkpoint
        therefore remains intact until the new one is fully written to disk.

    Why save scaler_state_dict (Micikevicius et al. 2018, Section 3.4):
        GradScaler maintains a dynamic loss scale factor (initially 2^16) and
        a counter of consecutive non-inf/non-nan steps.  After a gradient
        overflow, the scale is halved.  If scaler state is omitted on resume,
        the scaler restarts at 2^16 even if training was stable at, say, 2^8;
        the first backward pass at scale 2^16 may produce inf gradients,
        causing the scaler to halve repeatedly — wasting dozens of skipped
        optimizer steps.

    Google Drive mirror:
        Drive persists across Colab runtime resets; /content/ storage does
        not.  After the local atomic save, the checkpoint bytes are copied to
        Drive using pathlib byte I/O — no shutil import needed.  If Drive is
        not mounted (drive_checkpoint_dir does not exist), the copy is skipped
        with a warning rather than raising an error.

    Parameters
    ----------
    checkpoint_dir : local Path for checkpoint files (created if absent)
    global_step    : optimizer step count; embedded in the filename
    epoch          : current epoch index (0-based); saved for resume logic
    model          : BertForMLM instance
    optimizer      : AdamW instance
    scheduler      : LambdaLR instance
    scaler         : GradScaler instance (saved even when disabled)
    loss_history   : list of per-step mean losses accumulated so far
    config         : TrainingConfig (serialised as __dict__ for self-documentation)

    Returns
    -------
    Path to the saved checkpoint file (the final, non-.tmp path).
    """
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    name       = f"checkpoint_step{global_step:06d}.pt"
    final_path = checkpoint_dir / name
    tmp_path   = checkpoint_dir / (name + ".tmp")

    checkpoint: Dict[str, Any] = {
        "step":                 global_step,
        "epoch":                epoch,
        "model_state_dict":     model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict(),
        "scaler_state_dict":    scaler.state_dict(),   # critical for fp16 resume
        "loss_history":         loss_history,
        "config":               config.__dict__.copy(),
    }

    torch.save(checkpoint, tmp_path)
    os.replace(tmp_path, final_path)  # atomic rename on POSIX

    size_mb = final_path.stat().st_size / 1024 ** 2
    print(f"\n  [ckpt] Saved {final_path.name}  ({size_mb:.1f} MB)")

    if config.use_drive:
        drive_dir = Path(config.drive_checkpoint_dir)
        if drive_dir.exists():
            drive_dir.mkdir(parents=True, exist_ok=True)
            drive_path = drive_dir / name
            drive_path.write_bytes(final_path.read_bytes())  # byte-level copy
            print(f"  [ckpt] Mirrored → {drive_path}")
        else:
            print(f"  [ckpt] Drive dir not found ({drive_dir}) — skipping mirror.")

    sys.stdout.flush()          # Colab buffers stdout; force flush after checkpoint
    torch.cuda.empty_cache()    # free any cached allocator memory

    return final_path


def load_checkpoint(
    checkpoint_dir: Path,
    device: torch.device,
) -> Optional[Dict[str, Any]]:
    """
    Loads the most recent checkpoint from checkpoint_dir, or returns None.

    Why map_location='cpu' (not device):
        A checkpoint contains the model state dict AND AdamW optimizer states
        (the m and v moment tensors — one pair per parameter).  For a 17.6 M-
        parameter model in fp32, the optimizer state alone is ~140 MB.  Loading
        directly onto the GPU while the model is already resident there would
        require holding two full copies of the model simultaneously on the GPU,
        risking CUDA OOM on smaller cards.  Loading to CPU first costs only
        host RAM; the caller then moves individual tensors to device after the
        existing GPU-resident model is updated in place via load_state_dict().

    Checkpoint selection:
        Scans checkpoint_dir for all files matching 'checkpoint_step*.pt',
        sorts them lexicographically.  Because the step number is zero-padded
        to 6 digits in the filename, lexicographic order coincides with numeric
        order — the last entry is always the most recent checkpoint.

    Parameters
    ----------
    checkpoint_dir : directory to scan for checkpoint files
    device         : logged for informational output only; caller moves tensors

    Returns
    -------
    Loaded checkpoint dict, or None if checkpoint_dir is empty or absent.
    """
    if not checkpoint_dir.exists():
        return None

    ckpt_files = sorted(checkpoint_dir.glob("checkpoint_step*.pt"))
    if not ckpt_files:
        return None

    latest = ckpt_files[-1]
    print(f"  [resume] Found checkpoint: {latest.name}")

    # weights_only=False: checkpoint contains non-tensor objects (dicts, lists)
    checkpoint = torch.load(latest, map_location="cpu", weights_only=False)
    print(f"  [resume] Resuming from step {checkpoint['step']} "
          f"(epoch {checkpoint['epoch']})")

    return checkpoint


# ── SECTION 4: DATASET ────────────────────────────────────────────────────────

class PreprocessedDataset(Dataset):
    """
    Wraps the pre-tokenised dataset.pt file and applies dynamic Whole Word
    Masking on every __getitem__ call.

    Why load from dataset.pt rather than re-tokenising at training time:
        BPE tokenisation of 2 M paragraphs takes ~1.6 min on a multi-core CPU
        (04_dataset.preprocess_and_save measured this).  Colab VMs are reset
        frequently; re-tokenising from the raw corpus on every session restart
        would add >1.5 min of overhead before the first gradient step.
        dataset.pt stores pre-computed LongTensors (input_ids, attention_mask)
        that load in ~10 s via torch.load() — a ~10× saving per session.

    Why masking is applied here (not in preprocess_and_save):
        RoBERTa (Liu et al. 2019, Section 4.1) found that dynamic masking —
        drawing a fresh random mask each training step — performs comparably to
        or marginally better than static masking baked in at preprocessing.
        With ~12 training epochs, dynamic masking exposes the model to ~12
        distinct masking patterns per sequence, multiplying effective data
        diversity without growing the dataset.  Static masking would repeat the
        same mask every time a sequence is revisited within an epoch.

    Parameters
    ----------
    pt_path : Path to dataset.pt; must contain keys 'input_ids' and
              'attention_mask', both LongTensors of shape (N, max_seq_len).
    vocab   : token-to-id dict from load_tokenizer; forwarded to apply_masking.
    """

    def __init__(self, pt_path: Path, vocab: dict) -> None:
        data = torch.load(pt_path, map_location="cpu", weights_only=False)
        self.input_ids      = data["input_ids"]       # (N, 128) LongTensor
        self.attention_mask = data["attention_mask"]  # (N, 128) LongTensor
        self.vocab          = vocab

        # Pre-compute once: IDs of tokens whose string ends with '</w>'.
        # Identical to FinnishMLMDataset.__init__ in 04_dataset.py — avoids
        # rebuilding this frozenset on every __getitem__ call (O(vocab_size)
        # = O(50 000) per sample).
        self.end_of_word_ids: frozenset = frozenset(
            tid for tok, tid in vocab.items() if tok.endswith("</w>")
        )

    def __len__(self) -> int:
        return len(self.input_ids)

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        """
        Returns one masked training example.

        Raw token IDs from dataset.pt are converted to list[int] because
        apply_masking expects Python lists.  The returned dict contains three
        (128,) LongTensors matching the shape contract of collate_fn in
        04_dataset.py (torch.stack requires identical shapes).
        """
        token_ids      = self.input_ids[idx].tolist()  # list[int], len=128
        attention_mask = self.attention_mask[idx]       # LongTensor(128,)

        # Fresh random mask every call — dynamic masking (RoBERTa)
        masked_ids, labels = apply_masking(
            token_ids, self.vocab, self.end_of_word_ids
        )

        return {
            "input_ids":      torch.tensor(masked_ids, dtype=torch.long),
            "attention_mask": attention_mask,                                # already a tensor
            "labels":         torch.tensor(labels,    dtype=torch.long),
        }


# ── SECTION 5: TRAIN ──────────────────────────────────────────────────────────

def train(config: TrainingConfig) -> List[float]:
    """
    Main pre-training loop for Finnish BERT MLM.

    Implements:
      · Linear warmup + cosine decay LR schedule (Xiong 2020, RoBERTa)
      · AdamW with weight-matrix-only weight decay (Loshchilov & Hutter 2019)
      · fp16 mixed precision with GradScaler (Micikevicius et al. 2018)
      · Gradient accumulation — effective batch = 512 (BERT / RoBERTa)
      · Gradient clipping to max_norm=1.0 (RoBERTa)
      · Step-level checkpoint resume
      · Atomic checkpoint saving with Google Drive mirror
      · Dynamic Whole Word Masking per epoch (RoBERTa)

    Why step-level resume instead of epoch-level:
        Saving only the epoch number requires re-iterating from the start of
        the epoch after a restart.  At batches_per_epoch ≈ 15 625, a mid-epoch
        crash wastes up to ~7 min of A100 time just on DataLoader iteration.
        Step-level resume tracks the exact optimizer step and computes the
        corresponding batch index within the current epoch, skipping only the
        already-processed batches.  DataLoader shuffle state is not restored:
        the batch order within the resumed epoch differs from the original run,
        which is acceptable because MLM training is robust to intra-epoch batch
        ordering (each sample still contributes the same gradient signal over
        the full epoch, just in a different order).

    Parameters
    ----------
    config : TrainingConfig with all hyperparameters

    Returns
    -------
    loss_history : list of per-optimizer-step mean losses
    """

    # ── a) Reproducibility ────────────────────────────────────────────────────
    random.seed(config.seed)
    torch.manual_seed(config.seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(config.seed)
    # Note: CUDA non-determinism (e.g. atomics in attention) is NOT disabled
    # here — torch.use_deterministic_algorithms(True) cuts throughput ~30%.
    # The seed fixes the masking pattern and shuffle order for fresh runs only.

    # ── b) Device setup ───────────────────────────────────────────────────────
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device : {device}")
    if device.type == "cuda":
        props = torch.cuda.get_device_properties(0)
        print(f"  GPU  : {props.name}")
        print(f"  VRAM : {props.total_memory / 1e9:.1f} GB")

    # ── Load tokenizer ────────────────────────────────────────────────────────
    root_dir = Path(__file__).resolve().parent.parent
    print("\nLoading tokenizer...")
    vocab, merges = load_tokenizer(root_dir / config.tokenizer_dir)
    print(f"  vocab size : {len(vocab):,}  |  merge rules: {len(merges):,}")

    # ── Load dataset ──────────────────────────────────────────────────────────
    pt_path = root_dir / config.dataset_path
    print(f"\nLoading dataset from {pt_path} ...")
    dataset = PreprocessedDataset(pt_path, vocab)
    print(f"  {len(dataset):,} samples")

    # ── c) DataLoader ─────────────────────────────────────────────────────────
    loader = DataLoader(
        dataset,
        batch_size         = config.batch_size,
        shuffle            = True,
        num_workers        = 0 if sys.platform == "darwin" else 2,
        # macOS uses 'spawn' multiprocessing start method; classes loaded via
        # importlib cannot be pickled for worker processes, causing PicklingError.
        # Linux (Colab) uses 'fork' which copies the parent process memory directly
        # — no pickling needed, num_workers=2 works fine.
        # Windows also uses 'spawn' so set to 0 there too.
        pin_memory         = (device.type == "cuda"),  # async CPU → GPU DMA
        drop_last          = True,    # keeps batches_per_epoch constant (needed for resume math)
        persistent_workers = False,   # Colab uses 'spawn' multiprocessing; persistent workers
                                      # can deadlock on session restart
    )

    batches_per_epoch = len(loader)
    total_batches     = config.max_steps * config.grad_accum_steps
    n_epochs          = math.ceil(total_batches / batches_per_epoch)
    warmup_steps      = int(config.max_steps * config.warmup_ratio)

    print(f"\nTraining schedule:")
    print(f"  batches/epoch : {batches_per_epoch:,}")
    print(f"  n_epochs      : {n_epochs}")
    print(f"  max_steps     : {config.max_steps:,}")
    print(f"  warmup_steps  : {warmup_steps:,}")
    print(f"  eff. batch    : {config.batch_size * config.grad_accum_steps:,}  "
          f"(batch_size {config.batch_size} × grad_accum {config.grad_accum_steps})")

    # ── Build model ───────────────────────────────────────────────────────────
    print("\nBuilding model...")
    bert_cfg = BertConfig()
    model    = BertForMLM(bert_cfg).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Parameters: {n_params / 1e6:.2f} M")
    print(f"  hidden={bert_cfg.hidden_size}  layers={bert_cfg.num_layers}  "
          f"heads={bert_cfg.num_heads}  ffn={bert_cfg.ffn_size}")

    # ── d) Optimizer: AdamW with selective weight decay ───────────────────────
    #
    # Loshchilov & Hutter 2019 (AdamW, arXiv:1711.05101) demonstrate that
    # applying L2 weight decay to bias terms and LayerNorm parameters is
    # harmful: these parameters have different gradient scales than weight
    # matrices, and penalising them pushes them toward zero without providing
    # the intended regularisation benefit.  Devlin et al. 2019 (BERT) apply
    # weight decay only to weight matrices following this reasoning.
    #
    # We identify no-decay parameters by name:
    #   "bias"             → all Linear and Embedding bias vectors
    #   "layer_norm.*"     → BertEmbeddings.layer_norm (weight + bias)
    #   "norm1.*"          → TransformerEncoderBlock.norm1 (weight + bias)
    #   "norm2.*"          → TransformerEncoderBlock.norm2 (weight + bias)
    #   "mlm_norm.*"       → BertForMLM.mlm_norm (weight + bias)
    no_decay_keywords = (
        "bias",
        "layer_norm.weight", "layer_norm.bias",
        "norm1.weight",      "norm1.bias",
        "norm2.weight",      "norm2.bias",
        "mlm_norm.weight",   "mlm_norm.bias",
    )

    decay_params: List[torch.Tensor]    = []
    no_decay_params: List[torch.Tensor] = []
    for name, param in model.named_parameters():
        if not param.requires_grad:
            continue
        if any(kw in name for kw in no_decay_keywords):
            no_decay_params.append(param)
        else:
            decay_params.append(param)

    optimizer = torch.optim.AdamW(
        [
            {"params": decay_params,    "weight_decay": config.weight_decay},
            {"params": no_decay_params, "weight_decay": 0.0},
        ],
        lr    = config.lr,
        betas = (config.beta1, config.beta2),
        eps   = config.eps,
    )

    # ── e) LR scheduler ───────────────────────────────────────────────────────
    scheduler = get_lr_scheduler(optimizer, warmup_steps, config.max_steps)

    # ── f) GradScaler for fp16 ────────────────────────────────────────────────
    # enabled=False makes all scaler operations no-ops, so the same code path
    # handles both fp16 (CUDA) and fp32 (CPU) without any branching.
    fp16_active = config.use_fp16 and device.type == "cuda"
    scaler      = torch.cuda.amp.GradScaler(enabled=fp16_active)
    print(f"\nfp16 mixed precision: {'ON' if fp16_active else 'OFF'}")

    # ── g) Checkpoint resume ──────────────────────────────────────────────────
    global_step:  int        = 0
    loss_history: List[float] = []
    start_epoch:  int        = 0

    ckpt = load_checkpoint(Path(config.checkpoint_dir), device)
    if ckpt is not None:
        model.load_state_dict(ckpt["model_state_dict"])

        optimizer.load_state_dict(ckpt["optimizer_state_dict"])
        # Optimizer m/v moment tensors were loaded to CPU by map_location='cpu'.
        # Move them to device now that the model is already resident there.
        for state in optimizer.state.values():
            for k, v in state.items():
                if isinstance(v, torch.Tensor):
                    state[k] = v.to(device)

        scheduler.load_state_dict(ckpt["scheduler_state_dict"])
        scaler.load_state_dict(ckpt["scaler_state_dict"])

        global_step  = ckpt["step"]
        start_epoch  = ckpt["epoch"]
        loss_history = ckpt["loss_history"]
        print(f"  Resumed: step {global_step} / epoch {start_epoch}")

    # Compute how many batches within the resume epoch to skip.
    # resume_batch_step = total batch iterations completed before the checkpoint.
    # batches_before_resume_epoch = batches from all fully-completed epochs.
    # batches_to_skip = batches already done within the current (resume) epoch.
    resume_batch_step           = global_step * config.grad_accum_steps
    batches_before_resume_epoch = start_epoch * batches_per_epoch
    batches_to_skip             = max(0, resume_batch_step - batches_before_resume_epoch)

    # ── h) Training loop ──────────────────────────────────────────────────────
    model.train()
    start_time   = time.time()
    running_loss = 0.0  # cumulative raw loss over current grad_accum window
    accum_count  = 0    # batch counter within current grad_accum window
    optimizer.zero_grad(set_to_none=True)  # set_to_none=True is more memory-efficient
                                            # than zeroing: freed tensors return to the
                                            # allocator immediately (PyTorch docs)

    pbar = tqdm(
        total         = config.max_steps,
        initial       = global_step,
        desc          = "Training",
        unit          = "step",
        dynamic_ncols = True,
    )

    print(f"\nStarting training  step {global_step}/{config.max_steps}")
    if batches_to_skip > 0:
        print(f"  Skipping {batches_to_skip:,} batches in epoch {start_epoch} ...")

    epoch = start_epoch  # fallback: if range is empty, epoch is still defined
    for epoch in range(start_epoch, n_epochs):

        for batch_idx, batch in enumerate(loader):

            # ── Skip already-processed batches (no GPU work) ──────────────────
            # Only skip within the first (resume) epoch; in subsequent epochs
            # batches_to_skip is 0 so this branch is never taken.
            if epoch == start_epoch and batch_idx < batches_to_skip:
                continue

            # ── Move batch to device ──────────────────────────────────────────
            input_ids      = batch["input_ids"].to(device, non_blocking=True)
            attention_mask = batch["attention_mask"].to(device, non_blocking=True)
            labels         = batch["labels"].to(device, non_blocking=True)

            # ── Forward pass in fp16 autocast ─────────────────────────────────
            # torch.autocast casts eligible operations (matmul, conv) to fp16
            # while keeping accumulations and softmax in fp32 for stability.
            # enabled=False is a no-op, allowing identical code for fp32.
            with torch.autocast(
                device_type = device.type,
                dtype       = torch.float16,
                enabled     = fp16_active,
            ):
                loss, _logits = model(input_ids, attention_mask, labels)
                # Divide before backward: the gradients from each micro-batch
                # will be summed by .backward() calls; dividing by
                # grad_accum_steps converts the sum to a mean, equivalent to
                # computing the gradient on the full effective batch at once.
                scaled_loss = loss / config.grad_accum_steps

            # ── Backward ──────────────────────────────────────────────────────
            scaler.scale(scaled_loss).backward()
            running_loss += loss.item()  # accumulate raw (unscaled) loss for logging
            accum_count  += 1

            # ── Optimizer step after full accumulation window ─────────────────
            if accum_count == config.grad_accum_steps:

                # Unscale before clipping: clip_grad_norm_ operates on the
                # true gradients, not the fp16-scaled ones.
                scaler.unscale_(optimizer)
                torch.nn.utils.clip_grad_norm_(
                    model.parameters(), config.max_grad_norm
                )

                scaler.step(optimizer)    # skips step if grads contain inf/nan
                scaler.update()           # adjusts loss scale for next iteration
                scheduler.step()
                optimizer.zero_grad(set_to_none=True)

                step_loss    = running_loss / config.grad_accum_steps
                running_loss = 0.0
                accum_count  = 0
                global_step += 1
                loss_history.append(step_loss)

                pbar.update(1)
                pbar.set_postfix(
                    loss = f"{step_loss:.4f}",
                    ppl  = f"{math.exp(min(step_loss, 20)):.1f}",
                    lr   = f"{scheduler.get_last_lr()[0]:.2e}",
                )

                # ── Logging ───────────────────────────────────────────────────
                if global_step % config.log_every == 0:
                    elapsed       = time.time() - start_time
                    steps_per_sec = global_step / elapsed if elapsed > 0 else 0.0
                    eta_min       = (
                        (config.max_steps - global_step) / steps_per_sec / 60
                        if steps_per_sec > 0 else 0.0
                    )
                    print(
                        f"\nstep {global_step:>6}/{config.max_steps} | "
                        f"loss {step_loss:.4f} | "
                        f"ppl {math.exp(min(step_loss, 20)):6.1f} | "
                        f"{steps_per_sec:.2f} steps/s | "
                        f"ETA {eta_min:.1f} min | "
                        f"lr {scheduler.get_last_lr()[0]:.2e} | "
                        f"epoch {epoch}"
                    )
                    sys.stdout.flush()  # Colab line-buffers stdout; force flush

                # ── Checkpoint ────────────────────────────────────────────────
                if global_step % config.checkpoint_every == 0:
                    model.eval()   # consistent eval state during state_dict()
                    save_checkpoint(
                        checkpoint_dir = Path(config.checkpoint_dir),
                        global_step    = global_step,
                        epoch          = epoch,
                        model          = model,
                        optimizer      = optimizer,
                        scheduler      = scheduler,
                        scaler         = scaler,
                        loss_history   = loss_history,
                        config         = config,
                    )
                    model.train()  # restore train mode after checkpoint

                if global_step >= config.max_steps:
                    break  # inner loop

        if global_step >= config.max_steps:
            break  # outer loop

    pbar.close()

    # ── i) Final checkpoint ───────────────────────────────────────────────────
    print("\nTraining complete. Saving final checkpoint...")
    model.eval()
    save_checkpoint(
        checkpoint_dir = Path(config.checkpoint_dir),
        global_step    = global_step,
        epoch          = epoch,
        model          = model,
        optimizer      = optimizer,
        scheduler      = scheduler,
        scaler         = scaler,
        loss_history   = loss_history,
        config         = config,
    )
    model.train()

    elapsed = time.time() - start_time
    print(f"\nTotal time  : {elapsed / 60:.1f} min")
    print(f"Final loss  : {loss_history[-1]:.4f}")
    print(f"Final ppl   : {math.exp(min(loss_history[-1], 20)):.1f}")

    # ── j) Return loss history ────────────────────────────────────────────────
    return loss_history


# ── SECTION 6: MAIN ───────────────────────────────────────────────────────────

def main() -> None:
    """
    Entry point: mounts Google Drive (if in Colab), validates paths, builds
    config, and calls train().
    """

    # ── 1. Config ──────────────────────────────────────────────────────────────
    config = TrainingConfig()
    print("TrainingConfig")
    print("─" * 50)
    for k, v in config.__dict__.items():
        print(f"  {k:<30} = {v}")
    print("─" * 50)

    # ── 2. Google Drive mount ──────────────────────────────────────────────────
    try:
        from google.colab import drive  # type: ignore[import]
        mount_point = "/content/drive"
        if not Path(mount_point).exists():
            drive.mount(mount_point)
            print(f"Drive mounted at {mount_point}")
        else:
            print(f"Drive already mounted at {mount_point}")
    except ImportError:
        print("Not running in Colab — skipping Drive mount.")
        config.use_drive = False  # disable Drive mirror to avoid FileNotFoundError

    # ── 3. Path validation ─────────────────────────────────────────────────────
    root_dir = Path(__file__).resolve().parent.parent

    pt_path = root_dir / config.dataset_path
    if not pt_path.exists():
        raise FileNotFoundError(
            f"Pre-processed dataset not found: {pt_path}\n"
            "Run  python src/04_dataset.py  first to generate dataset.pt."
        )

    tok_dir = root_dir / config.tokenizer_dir
    if not tok_dir.exists():
        raise FileNotFoundError(
            f"Tokenizer directory not found: {tok_dir}\n"
            "Run  python src/03_tokenizer.py  first."
        )

    # ── 4. Train ───────────────────────────────────────────────────────────────
    loss_history = train(config)

    # ── 5. Summary ─────────────────────────────────────────────────────────────
    if loss_history:
        n_last        = min(100, len(loss_history))
        avg_last      = sum(loss_history[-n_last:]) / n_last
        final_loss    = loss_history[-1]
        final_ppl     = math.exp(min(final_loss, 20))
        initial_loss  = loss_history[0]

        print("\n── Final Summary " + "─" * 34)
        print(f"  Steps completed     : {len(loss_history):,}")
        print(f"  Initial loss        : {initial_loss:.4f}  "
              f"(random-init expected ≈ {math.log(50_000):.2f} = ln(50 000))")
        print(f"  Final loss          : {final_loss:.4f}")
        print(f"  Avg loss (last {n_last:>3}) : {avg_last:.4f}")
        print(f"  Final perplexity    : {final_ppl:.1f}")
        print("─" * 50)


if __name__ == "__main__":
    main()
